# Generated by Django 4.2.1 on 2023-09-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app_backend', '0002_blacklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='movie',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='movie_id',
            field=models.IntegerField(null=True),
        ),
    ]
