# Generated by Django 4.2.1 on 2023-10-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app_backend', '0004_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
